version: "3.4"

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"